### ISSUE TITLE
GoogleStaticMap' not found

### ISSUE THREAD

**Issue by tenoimelda** [nmfzone/google-static-map-laravel#1]
in my controller 
 public function index () {
    	GoogleStaticMap::make('-7.797068', '110.370529')->setCenter('Indonesia')->setZoom('4')->getUrl();
    	return view('b');
    }
in my view
<div>
	 <div style="width: 1000px; height: 400px;">
	 	{!! GoogleStaticMap::render() !!}
	 </div>
</div>

help

**Comment by nmfzone** [comment]
@tenoimelda What do you mean? Is there any error? You should describe about what's going on..

**Comment by tenoimelda** [comment]
I created a function in the controller, but when we try to call,
GoogleStaticMap not found error class, I have added the class to the app
config, and can you give a simple example of how the function is on the
controller? because i'm still a beginner

Pada tanggal 24 Jul 2019 13.42, "Nabil Muh. Firdaus" <
notifications@github.com> menulis:

**Comment by nmfzone** [comment]
@tenoimelda Ok, but since you're not describing about what's going on, I'll give an example based on my understanding. This package is used only to create a url of the static map, so if you want to use in the view, you just need to placed generated URL in the `img` tag.

Controller
```
use GoogleStaticMap;

class Welcome extends Controller
{
    public function show()
    {
        $staticUrl = GoogleStaticMap::make('-7.797068', '110.370529')->getUrl();

        return view('your_view_name', compact('staticUrl'));
    }
}
```

View
```
<img src="{{ $staticUrl }}" />
```

just simple as like that.

**Comment by tenoimelda** [comment]
Thank you for giving an example, but I still get app \ http \ Controller \
GoogleStaticMap not found errors, when I have added it in the config \ app,
aliases 'GoogleStaticMap' => MNFCODES \ GoogleStaticMap \
GoogleStaticMapFacades :: class, then I add to the provider too, is there a
code that needs to be called again on the controller? for example use
GoogleStaticMap, thank you

Pada tanggal 25 Jul 2019 09.30, "Nabil Muh. Firdaus" <
notifications@github.com> menulis:

**Comment by nmfzone** [comment]
@tenoimelda I've give you complete example in my previous comment, please read it carefully.
What's laravel version you're using? if you use Laravel 5.5, you just need to install, then do nothing, don't need to add anything to the config/app.php.

**Comment by tenoimelda** [comment]
I use laravel 5.4 and php 7, did I make a mistake? If yes, let me know,
thank you for taking the time

Pada tanggal 25 Jul 2019 10.56, "Nabil Muh. Firdaus" <
notifications@github.com> menulis:

**Comment by nmfzone** [comment]
@tenoimelda Oh, ok. Have you read my example code carefully? In this section:

```
use GoogleStaticMap;

class Welcome extends Controller
{
    public function show()
    {
        $staticUrl = GoogleStaticMap::make('-7.797068', '110.370529')->getUrl();

        return view('your_view_name', compact('staticUrl'));
    }
}
```

**Comment by tenoimelda** [comment]
Bang orang Indonesia ya, saya coba dm aja ya bang di instagram

Pada tanggal 25 Jul 2019 11.13, "Nabil Muh. Firdaus" <
notifications@github.com> menulis:

**Comment by nmfzone** [comment]
@tenoimelda Hzzzzzz, nope. Just use this comment section & be english 😄

**Comment by tenoimelda** [comment]
Wkwkwk haduh, bang ayolah bantu dulu 🙏🙏🙏🙏

Pada tanggal 25 Jul 2019 11.31, "Nabil Muh. Firdaus" <
notifications@github.com> menulis:

**Comment by nmfzone** [comment]
@tenoimelda haha, nope nope. Jelaskan aja lewat sini, biar bermanfaat buat yg lain.

**Comment by tenoimelda** [comment]
Oke bang, jadi gini saya sudah buat function intinya udah semua banh, nah
yg saya bingung kenapa masih not found GoogleStaticMap, nahh kalo kaya
package lain kan tinggal tambah kan di controller use bla bla bla,  nahh
kira kira kenapa ya bang soal not found GoogleStaticMap, terimakasih bang
atas respon nya

Pada tanggal 25 Jul 2019 11.34, "Nabil Muh. Firdaus" <
notifications@github.com> menulis:

**Comment by nmfzone** [comment]
@tenoimelda Use english please 😄 

Perhatikan contoh yg udah tak berikan, harusnya sudah jelas lho. Kecuali emang kalau kode yg tak bikin ada yg ngebug.

Udah ada bagian ini?

```
use GoogleStaticMap;
```

**Comment by tenoimelda** [comment]
Ok, succesfully but, once i compact variabel for my view undifined
variabel, do i have looping foreach?

Pada tanggal 25 Jul 2019 11.38, "Nabil Muh. Firdaus" <
notifications@github.com> menulis:

**Comment by nmfzone** [comment]
@tenoimelda hemmmmm, as I suspect.

I don't know your code, so please use something like https://codeshare.io, so I can re check your code.

**Comment by tenoimelda** [comment]
This my link,
https://codeshare.io/5QLjnW
please tell me if i wrong, i think its possible to call the variable wrong
in the view
duh bang, kalo ada typo penulisan kasih tau pliss

**Comment by nmfzone** [comment]
@tenoimelda I've read your code, and as I suspect, you don't read my example code **carefully**. The usage of PHP `compact` isn't like that. You should write it like this:

```
compact('real')
```

Each params in `compact` represent each variable before it.

**Comment by tenoimelda** [comment]
Yeahh It works, but the map hasn't appeared yet, does Google Maps have to
be added to the key API?

Pada tanggal 25 Jul 2019 12.32, "Nabil Muh. Firdaus" <
notifications@github.com> menulis:

**Comment by nmfzone** [comment]
Of course dude. You should've Google Maps API key.

**Comment by tenoimelda** [comment]
Okeeey thank you very much 🙏

Pada tanggal 25 Jul 2019 13.13, "Nabil Muh. Firdaus" <
notifications@github.com> menulis:

**Comment by nmfzone** [comment]
@tenoimelda You're welcome! Star this package if you found this package is useful 🥇
